# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.3.6"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.4/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]


    [notes.updates]
        title = "Component Updates"
        description = """\
* Gvisor: 20231214.0
* Linux firmware: 20230310
* Intel ucode: 20230214
* nvidia-container-toolkit: v1.12.1
* NVIDIA driver: 530.41.03
* nvidia-fabricmanager: 525.85.12
"""


[make_deps]
